In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv("flipkart.csv")
data.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   uniq_id                  20000 non-null  object 
 1   crawl_timestamp          20000 non-null  object 
 2   product_url              20000 non-null  object 
 3   product_name             20000 non-null  object 
 4   product_category_tree    20000 non-null  object 
 5   pid                      20000 non-null  object 
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object 
 9   is_FK_Advantage_product  20000 non-null  bool   
 10  description              19998 non-null  object 
 11  product_rating           20000 non-null  object 
 12  overall_rating           20000 non-null  object 
 13  brand                    14136 non-null  object 
 14  product_specifications

In [4]:
data.groupby("product_rating")['uniq_id'].count()

product_rating
1                        171
1.3                        4
1.5                        4
1.7                        4
1.8                        2
2                         80
2.2                        8
2.3                       12
2.4                        5
2.5                       23
2.6                        3
2.7                       10
2.8                       11
2.9                        5
3                        168
3.1                        7
3.2                       20
3.3                       17
3.4                       13
3.5                       45
3.6                       25
3.7                       51
3.8                       23
3.9                       15
4                        246
4.1                       24
4.2                       47
4.3                       45
4.4                       16
4.5                       67
4.6                        9
4.7                       24
4.8                       21
4.9                        4

In [5]:
data = data[['uniq_id','product_url','product_name','product_category_tree','image','description','brand']]
data.head()

uniq_id  \
0  c2d766ca982eca8304150849735ffef9   
1  7f7036a6d550aaa89d34c77bd39a5e48   
2  f449ec65dcbc041b6ae5e6a32717d01b   
3  0973b37acd0c664e3de26e97e5571454   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...   
1  ["Furniture >> Living Room Furniture >> Sofa B...   
2  ["Footwear >> Women's Footwear >> Ballerinas >...   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...   

                                               image  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...   

                                         description         brand  
0  Key Features of Alisha Solid Women's Cycling S...        Alisha  
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  FabHomeDecor  
2  Key Features of AW Bellies Sandals Wedges Heel...            AW  
3  Key Features of Alisha Solid Women's Cycling S...        Alisha  
4  Specifications of Sicons All Purpose Arnica Do...        Sicons

In [6]:
data.isnull().sum()

uniq_id                     0
product_url                 0
product_name                0
product_category_tree       0
image                       3
description                 2
brand                    5864
dtype: int64

In [7]:
data['image'] = data['image'].fillna("['#']")
data['description'] = data['description'].fillna("['']")
data['brand'] = data['brand'].fillna("['']")
# data['product_specifications'] = data['product_specifications'].fillna("")
data.isnull().sum()

uniq_id                  0
product_url              0
product_name             0
product_category_tree    0
image                    0
description              0
brand                    0
dtype: int64

In [8]:
import ast
def convert(obj):
    i = ast.literal_eval(obj)
    return i[0]

In [9]:
data['image'] = data['image'].apply(convert)
data['product_category_tree'] = data['product_category_tree'].apply(convert)
# data.head()

In [10]:
data['brand']= data['brand'].apply(lambda x: x.split())

In [11]:
def convert2(string):
    li = list(string.split(" "))
    return li

data['description'] = data['description'].apply(convert2) 

In [12]:
data['product_category_tree'] = data['product_category_tree'].apply(lambda x: x.split(">>"))

In [13]:
data['product_category_tree'] = data['product_category_tree'].apply(lambda x: [i.replace(" ","") for i in x])
data['brand'] = data['brand'].apply(lambda x: [i.replace(" ","") for i in x])
data['description'] = data['description'].apply(lambda x: [i.replace(" ","") for i in x])

# creating tags and converting to vector

In [14]:
data['tags'] = data['product_category_tree']+ data['brand']+data['description']
data['tags']=data['tags'].apply(lambda x: " ".join(x))
data['tags'] = data['tags'].apply(lambda x: x.lower())
data['tags'][9008]

"watches wristwatches hourglasswristwatches [''] hourglass hg 006 analog watch  - for men - buy hourglass hg 006 analog watch  - for men  hg 006 online at rs.850 in india only at flipkart.com. - great discounts, only genuine products, 30 day replacement guarantee, free shipping. cash on delivery!"

In [15]:
data.head(0)

Empty DataFrame
Columns: [uniq_id, product_url, product_name, product_category_tree, image, description, brand, tags]
Index: []

In [16]:
## new DataFrame
all_products = data[['uniq_id','product_name','product_url','image', 'tags']]
all_products.head()

uniq_id                           product_name  \
0  c2d766ca982eca8304150849735ffef9    Alisha Solid Women's Cycling Shorts   
1  7f7036a6d550aaa89d34c77bd39a5e48    FabHomeDecor Fabric Double Sofa Bed   
2  f449ec65dcbc041b6ae5e6a32717d01b                             AW Bellies   
3  0973b37acd0c664e3de26e97e5571454    Alisha Solid Women's Cycling Shorts   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  Sicons All Purpose Arnica Dog Shampoo   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                                               image  \
0  http://img5a.flixcart.com/image/short/u/4/a/al...   
1  http://img6a.flixcart.com/image/sofa-bed/j/f/y...   
2  http://img5a.flixcart.com/image/shoe/7/z/z/red...   
3  http://img5a.flixcart.com/image/short/6/2/h/al...   
4  http://img5a.flixcart.com/image/pet-shampoo/r/...   

                                                tags  
0  clothing women'sclothing lingerie,sleep&swimwe...  
1  furniture livingroomfurniture sofabeds&futons ...  
2  footwear women'sfootwear ballerinas awbellies ...  
3  clothing women'sclothing lingerie,sleep&swimwe...  
4  petsupplies grooming skin&coatcare shampoo sic...

In [17]:
products = all_products[:5000]
products.shape

(5000, 5)

# making vectors:

In [18]:
import nltk
from nltk.stem.porter import PorterStemmer
ps =  PorterStemmer()

In [19]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [20]:
products['tags'] = products['tags'].apply(stem)
# Stemming is used in information retrieval systems like search engines.
# It is used to determine domain vocabularies in domain analysis.
products.shape

<ipython-input-20-4c3e12176a53>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products['tags'] = products['tags'].apply(stem)


(5000, 5)

In [21]:
products.shape

(5000, 5)

In [22]:
all_products['tags'][0]

"cloth women'scloth lingerie,sleep&swimwear short alishashort alishasolidwomen'scyclingshort alisha key featur of alisha solid women' cycl short cotton lycra navy, red, navy,specif of alisha solid women' cycl short short detail number of content in sale packag pack of 3 fabric cotton lycra type cycl short gener detail pattern solid ideal for women' fabric care gentl machin wash in lukewarm water, do not bleach addit detail style code altht_3p_21 in the box 3 short"

In [23]:
import re
def no_number_preprocessor(tokens):
    r = re.sub('(\d)+', '', tokens.lower())
    # This alternative just removes numbers:
    # r = re.sub('(\d)+', '', tokens.lower())
    return r

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english', preprocessor=no_number_preprocessor)

In [25]:
vectors = cv.fit_transform(products['tags']).toarray()

In [26]:
cv.get_feature_names()

['_brn',
 'aa',
 'aaa',
 'aadivasi',
 'aadyaa',
 'aahana',
 'aaishwarya',
 'aakash',
 'aakshi',
 'aaliya',
 'aaliyatop',
 'aao',
 'aapno',
 'aara',
 'aaradhi',
 'ab',
 'abaya',
 'abhira',
 'abil',
 'abl',
 'aboni',
 'abov',
 'absolut',
 'absorb',
 'abstract',
 'absurd',
 'absurdsweatshirt',
 'ac',
 'accent',
 'accentu',
 'access',
 'accessor',
 'accessoreez',
 'accessori',
 'accessories',
 'accessoris',
 'accessory',
 'accid',
 'accord',
 'accu',
 'ace',
 'acheived',
 'achiev',
 'acid',
 'acm',
 'acoust',
 'acryl',
 'acrylic',
 'act',
 'action',
 'actionshoesslippers',
 'activ',
 'actual',
 'ad',
 'ada',
 'adaa',
 'adapt',
 'adapter',
 'add',
 'adde',
 'addict',
 'addit',
 'addition',
 'addon',
 'address',
 'addyvero',
 'aden',
 'adhes',
 'adhira',
 'adida',
 'adimani',
 'adiwalk',
 'adjust',
 'adjustable',
 'admir',
 'ador',
 'adorelabel',
 'adorn',
 'adroitz',
 'adt',
 'adult',
 'advanc',
 'advantage',
 'adventur',
 'adventures',
 'advika',
 'adwb',
 'adwitiya',
 'aeoss',
 'aerosoft'

In [27]:
vectors.shape

(5000, 5000)

In [28]:
# len(data['tags'].unique())

In [29]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [30]:
similarity.shape

(5000, 5000)

In [31]:
similarity

array([[1.        , 0.07760242, 0.17739372, ..., 0.        , 0.        ,
        0.        ],
       [0.07760242, 1.        , 0.21827459, ..., 0.02798914, 0.02279804,
        0.02242175],
       [0.17739372, 0.21827459, 1.        , ..., 0.02465943, 0.04017177,
        0.03160698],
       ...,
       [0.        , 0.02798914, 0.02465943, ..., 1.        , 0.2833153 ,
        0.36223084],
       [0.        , 0.02279804, 0.04017177, ..., 0.2833153 , 1.        ,
        0.36313652],
       [0.        , 0.02242175, 0.03160698, ..., 0.36223084, 0.36313652,
        1.        ]])

In [32]:
def recommend(product):
    product_index = products[products['product_name'] == product].index[0]
    distances = similarity[product_index]
    movie_list = sorted(list(enumerate(distances)), reverse= True, key = lambda x: x[1])[1:11]
    print(movie_list)
    for i in movie_list:
        print(products.iloc[i[0]].product_name)

In [33]:
recommend("FabHomeDecor Fabric Double Sofa Bed")

[(7, 0.9813448880030222), (16, 0.9813448880030222), (19, 0.9769144144144145), (3079, 0.6539385975614653), (3051, 0.5919661758623798), (3078, 0.5633397584768147), (3012, 0.560761530947408), (3036, 0.560761530947408), (3074, 0.5587242434461608), (3019, 0.49019992459114253)]
FabHomeDecor Fabric Double Sofa Bed
FabHomeDecor Fabric Double Sofa Bed
FabHomeDecor Fabric Double Sofa Bed
induscraft Solid Wood Computer Desk
IBS ADJUSTABLE FOLDING KIDS MATE HOME OFFICE READING WRITING TABLEMATE WITH CUPHOLDER Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS ADJUSTABLE FOLDING KIDS MATE HOME OFFICE READING WRITING TABLEMATE WITH CUPHOLDER Plastic Portable Laptop Table


In [34]:
z = list(enumerate(similarity))

In [35]:
z

[(0,
  array([1.        , 0.07760242, 0.17739372, ..., 0.        , 0.        ,
         0.        ])),
 (1,
  array([0.07760242, 1.        , 0.21827459, ..., 0.02798914, 0.02279804,
         0.02242175])),
 (2,
  array([0.17739372, 0.21827459, 1.        , ..., 0.02465943, 0.04017177,
         0.03160698])),
 (3,
  array([0.97631348, 0.08949875, 0.1802322 , ..., 0.        , 0.        ,
         0.        ])),
 (4,
  array([0.08391814, 0.0675866 , 0.09924367, ..., 0.        , 0.        ,
         0.        ])),
 (5,
  array([0.02869238, 0.12764683, 0.05429171, ..., 0.00683746, 0.05940612,
         0.00876384])),
 (6,
  array([0.984375  , 0.07760242, 0.18478512, ..., 0.        , 0.        ,
         0.        ])),
 (7,
  array([0.07795436, 0.98134489, 0.2192645 , ..., 0.02811608, 0.02290143,
         0.02252344])),
 (8,
  array([0.14392316, 0.15227902, 0.36844831, ..., 0.        , 0.        ,
         0.        ])),
 (9,
  array([0.9609375 , 0.09857605, 0.17739372, ..., 0.        , 0.    

In [36]:
import pickle as pkl
pkl.dump(z, open('5000_similarity.pkl','wb'))

In [37]:
# all_products.to_csv('all_products.csv')
products.to_csv('5000_products.csv')

In [40]:
recommend("IBS Plastic Portable Laptop Table")

[(3036, 1.0), (3074, 0.9981867754047642), (3078, 0.9981756394757433), (3019, 0.8999943336275813), (3033, 0.8932755574501081), (3051, 0.8238223474841426), (3079, 0.6731291686085963), (7, 0.5633046801892574), (16, 0.5633046801892574), (1, 0.560761530947408)]
IBS Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS Plastic Portable Laptop Table
IBS ADJUSTABLE FOLDING KIDS MATE HOME OFFICE READING WRITING TABLEMATE WITH CUPHOLDER Plastic Portable Laptop Table
IBS ADJUSTABLE FOLDING KIDS MATE HOME OFFICE READING WRITING STUDY TABLEMATE WITH CUPHOLDER Plastic Portable Laptop Table
IBS ADJUSTABLE FOLDING KIDS MATE HOME OFFICE READING WRITING TABLEMATE WITH CUPHOLDER Plastic Portable Laptop Table
induscraft Solid Wood Computer Desk
FabHomeDecor Fabric Double Sofa Bed
FabHomeDecor Fabric Double Sofa Bed
FabHomeDecor Fabric Double Sofa Bed
